name: Setup
description: Action Setup

runs:
  using: composite
  steps:
    - name: Check out code
      uses: actions/checkout@v4
  
    - name: "Install UV"
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Install dependencies
      shell: bash
      run: uv sync --all-extras --all-packages --group
